### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JaykeBird** [ceresgalax/CeresAudio#1]
Hello! I stumbled across this project while looking for C# bindings to Cubeb, and this seems like something matching what I was wanting.

One thing that I noticed is that this repo doesn't have any indication of a code license (or if there is one, I can't find it). I'd imagine the source was published here with the intent of being open-source, but obviously "open source" can mean different things to different people. Do you have a license in mind?

For reference, Cubeb itself [has a ISC License](https://github.com/mozilla/cubeb/blob/master/LICENSE), but you don't have to follow that.

**Comment by ceresgalax** [comment]
Hi there! This project is indeed intended to be open source. I have just added the ISC license. 

I have also thrown in a README and example code today. I hope this helps! Happy coding!

**Comment by JaykeBird** [comment]
Cool, thank you! And also thank you for the example code and readme too, that really helps!

I got a chance to look through it a little bit, although I'll probably start experimenting with it more in a month or so. I'm excited to try it all out! I'll post issues or try to contribute things as I can once I dive into it more.
